### PR TITLE
gulp frontend test

### PR DESCRIPTION
**Pull request by sb8244**
This is just an example of gulp on a real angular based project. For myself

### CODE REVIEW

**Comment by sb8244** [comment]
Howdy from Release Ninja! You should write a release note targeted at a semi-technical end user who is
not familiar with the code base. Include at least 1 image, wherever possible. [Review the help article](https://www.therelease.ninja/help) if
you are not familiar with Release Ninja.

When your pull request is ready, do one of the following:

* [Notify Release Team](https://www.therelease.ninja/workflow/review?project_id=3&pull_request_id=32&repository_id=3)
* Don't notify anyone because it's a small change or doesn't concern them
Whatever you do though, make sure you :tada:

**Comment by barberj** [comment]
perhaps this weekend you can give me a crash course on gulp, grunt or webpack

**Comment by barberj** [comment]
sorry clicked wrong button. they really should pull one right and one left.

**Comment by sb8244** [comment]
I can do gulp and grunt. Patrick for web pack

On Saturday, November 28, 2015, Justin <notifications@github.com> wrote:

> Reopened #32 <https://github.com/SalesLoft/release-ninja/pull/32>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SalesLoft/release-ninja/pull/32#event-476892788>.
>


-- 


  Steve Bussey •SalesLoft

•Software Engineer

e steve.bussey@salesloft.com w salesloft.com
<http://salesloft.com/?v=1&utm_expid=76406993-1.E5ncJhwyTAW9uGaR1WdBTA.1?utm_source=Email-Signature-Rescue&utm_medium=Email-Signature&utm_campaign=Email-Signature-Rescue>

a 3423 Piedmont Rd NE, Atlanta, GA 30305

[image: Facebook] <https://www.facebook.com/SalesLoft> [image: Twitter]
<https://twitter.com/SalesLoft> [image: Linkedin]
<https://www.linkedin.com/company/salesloft> [image: wordpress]
<http://blog.salesloft.com/blog/> [image:
http://salesloft.com/prospector/#video]
<http://salesloft.com/prospector/#video>  [image: Software Engineer Logo]
<http://salesloft.com/?v=1&utm_expid=76406993-1.E5ncJhwyTAW9uGaR1WdBTA.1?utm_source=Email-Signature-Rescue&utm_medium=Email-Signature&utm_campaign=Email-Signature-Rescue>

**Pull request closed without merging**
