### PR TITLE
Persist PullRequests

### PR DESCRIPTION
**Pull request by barberj**
# New Feature - Persist PullRequests to Database

Persist key attributes of a pull request to the database.

### CODE REVIEW

**Comment by sb8244** [comment]
Howdy from Release Ninja! You should write a release note targeted at a semi-technical end user who is
not familiar with the code base. Include at least 1 image, wherever possible. [Review the help article](https://www.therelease.ninja/help) if
you are not familiar with Release Ninja.

When your pull request is ready, do one of the following:

* [Notify Release Team](https://www.therelease.ninja/workflow/review?project_id=3&pull_request_id=29&repository_id=3)
* Don't notify anyone because it's a small change or doesn't concern them
Whatever you do though, make sure you :tada:

**Comment by barberj** [comment]
@sb8244 - No front end, but in case you wanted to continue where we left off.

**Comment by sb8244** [comment]
Thanks!

On Thursday, July 16, 2015, Justin <notifications@github.com> wrote:

> @sb8244 <https://github.com/sb8244> - No front end, but in case you
> wanted to continue where we left off.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SalesLoft/release-ninja/pull/29#issuecomment-122135696>
> .
>


-- 


  Steve Bussey •SalesLoft

•Software Engineer

e steve.bussey@salesloft.com w salesloft.com
<http://salesloft.com/?v=1&utm_expid=76406993-1.E5ncJhwyTAW9uGaR1WdBTA.1?utm_source=Email-Signature-Rescue&utm_medium=Email-Signature&utm_campaign=Email-Signature-Rescue>

a 3423 Piedmont Rd NE, Atlanta, GA 30305

[image: Facebook] <https://www.facebook.com/SalesLoft> [image: Twitter]
<https://twitter.com/SalesLoft> [image: Linkedin]
<https://www.linkedin.com/company/salesloft> [image: wordpress]
<http://blog.salesloft.com/blog/> [image:
http://salesloft.com/prospector/#video]
<http://salesloft.com/prospector/#video>  [image: Software Engineer Logo]
<http://salesloft.com/?v=1&utm_expid=76406993-1.E5ncJhwyTAW9uGaR1WdBTA.1?utm_source=Email-Signature-Rescue&utm_medium=Email-Signature&utm_campaign=Email-Signature-Rescue>

**Comment by sb8244** [comment]
Howdy from Release Ninja! I just created a note and sent out emails to steve@salesloft.com, patrick.wiseman@salesloft.com
:tada:

**Pull request merged**
