### PR TITLE
simplify setup for sending emails from development

### PR DESCRIPTION
**Pull request by dewetblomerus**
Hi there, thanks for building & open sourcing Release Ninja & for the exceptional documentation. 

Streamline the setup of sending emails from development, specifically removing the need to edit development.rb

### CODE REVIEW

**Comment by sb8244** [comment]
Howdy from Release Ninja! You should write a release note targeted at a semi-technical end user who is
not familiar with the code base. Include at least 1 image, wherever possible. [Review the help article](https://www.therelease.ninja/help) if
you are not familiar with Release Ninja.

When your pull request is ready, do one of the following:

* [Notify Release Team](https://www.therelease.ninja/workflow/review?project_id=3&pull_request_id=37&repository_id=3)
* Don't notify anyone because it's a small change or doesn't concern them
Whatever you do though, make sure you :tada:

**Comment by sb8244** [comment]
Have you ever seen a program like fake smtp? It starts an smtp server on port 1025 locally, but black holes it so you can read everything that goes through it.

I believe these programs lead to a better local development experience because they can be used offline without change.

**Comment by sb8244** [comment]
https://nilhcem.github.io/FakeSMTP/ Here is a link to fake smtp.

**Comment by dewetblomerus** [comment]
Hey thanks a ton for the advice! I didn't know about fake smtp. I'm happy to go with fake smtp instead so I'll close this pull request. If I do want to make a contribution, do you suggest I start with the issue you opened about "Automatic project acceptance" or something else?

**Comment by sb8244** [comment]
Awesome! Super excited to hear that. im going to prune the issues that I haven't put up here to find a good one to start with! I did some changes to the invite system that closes that issue, already.

**Comment by dewetblomerus** [comment]
Thanks Stephen,
Please don't feel pressured to get back to me today, it is Sunday, and even if it wasn't, it's bed time in my time zone.

**Pull request closed without merging**
